DELETE FROM DEBT_CATEGORY;

INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (1, 'FOOD', 'debt.category.food', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (2, 'TRANSPORT', 'debt.category.transport', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (3, 'ENTERTAINMENT', 'debt.category.entertainment', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (4, 'SERVICES', 'debt.category.services', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (5, 'HEALTH', 'debt.category.health', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (6, 'LOAN', 'debt.category.loan', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (7, 'CREDIT_CARD', 'debt.category.creditCard', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (8, 'EDUCATION', 'debt.category.education', true);
INSERT INTO DEBT_CATEGORY (ID, NAME, DESCRIPTION, GLOBAL) VALUES (9, 'OTHER', 'debt.category.other', true);
