DELETE FROM DEBT_PRIORITY;

INSERT INTO DEBT_PRIORITY (ID, NAME, DESCRIPTION, GLOBAL, COLOR) VALUES (1, 'LOW', 'debt.priority.low', true, '#23ed26');
INSERT INTO DEBT_PRIORITY (ID, NAME, DESCRIPTION, GLOBAL, COLOR) VALUES (2, 'MEDIUM', 'debt.priority.medium', true, '#dfe527');
INSERT INTO DEBT_PRIORITY (ID, NAME, DESCRIPTION, GLOBAL, COLOR) VALUES (3, 'HIGH', 'debt.priority.high', true, '#e82929');